### ISSUE TITLE
python run_gpulearn_z_x.py mnist got some problem

### ISSUE THREAD

**Issue by StevenLOL** [dpkingma/nips14-ssl#3]
Hi, I follow your steps and got error when calling

python run_gpulearn_z_x.py mnist 

```
python run_gpulearn_z_x.py mnist
logdir: results/gpulearn_z_x_mnist_50-(500, 500)__1432466595/
gpulearn_z_x 50 (500, 500) mnist 0
AdaM 0.0003 0.1 0.001 0.02
Variational Auto-Encoder 1000
Traceback (most recent call last):
  File "run_gpulearn_z_x.py", line 10, in <module>
    gpulearn_z_x.main(dataset='mnist', n_z=50, n_hidden=n_hidden, seed=0, comment='', gfx=True)
  File "/home/steven/nips14-ssl/gpulearn_z_x.py", line 369, in main
    loop_va(dostep, hook)
  File "/home/steven/nips14-ssl/gpulearn_z_x.py", line 378, in loop_va
    L = doEpoch()
  File "/home/steven/nips14-ssl/gpulearn_z_x.py", line 402, in doEpoch
    L += model.evalAndUpdate(x_minibatch, {}).sum()
  File "/home/steven/nips14-ssl/anglepy/GPUVAEModel.py", line 110, in evalAndUpdate
    L = self.f_evalAndUpdate(*allvars)
  File "/home/steven/nips14-ssl/anglepy/misc.py", line 81, in func
    f[0] = theano.function(*args, **kwargs)
  File "/home/steven/src/theano/theano/compile/function.py", line 265, in function
    profile=profile)
  File "/home/steven/src/theano/theano/compile/pfunc.py", line 489, in pfunc
    no_default_updates=no_default_updates)
  File "/home/steven/src/theano/theano/compile/pfunc.py", line 217, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')
```

**Comment by sergulaydore** [comment]
I fixed the issue by replacing all the floats with np.float32() in get_optimizer function. For example:

fix1 = np.float32(1.)-(np.float32(1.)-np.float32(decay1))**(it+np.float32(1.))

**Comment by StevenLOL** [comment]
Thanks @sergulaydore
